[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1"
backend-core = { path = "../backend-core" }
chrono = { version = "0.4", features = [ "serde" ] }
rand = "*"
rust_decimal = "1.29"
tokio = { version = "1.28", features = ["rt", "macros"] }

[dependencies.sea-orm-migration]
version = "0.11"
features = [
   "runtime-tokio-rustls",
   "sqlx-sqlite",
]
